name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run linting
        run: uv run ruff check

      - name: Run type checking
        run: uv run ty check

      - name: Publish package
        if: github.event_name == 'release' && github.event.action == 'published'
        run: |
          uv build
          uv publish --token ${{ secrets.PYPI_TOKEN }}
